services:
    _defaults:
        autowire: true

    Sherlockode\UserConfirmationBundle\Controller\:
        resource: '../../Controller/*'
        tags: ['controller.service_arguments']
    Sherlockode\UserConfirmationBundle\Manager\:
        resource: '../../Manager/*'

    Sherlockode\UserConfirmationBundle\Manager\MailManager:
        arguments:
            $senderEmail: '%sherlockode_user_confirmation.from_email%'
            $confirmationEmailTemplate: '%sherlockode_user_confirmation.templates.confirmation_email%'
            $emailSubject: '%sherlockode_user_confirmation.email_subject%'
    Sherlockode\UserConfirmationBundle\EventListener\UserListener:
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: postPersist }

